In [3]:
#this is a revised version of the code. the functions are run in the bottom using user input,
#which will be replaced by client side interaction


import pytraj as pt

In [4]:
#this function is what gathers the calculations over random timeframes with given number of samples and timesteps
import datetime
import random

def gatherData(traj):
    timeSteps = input("Enter number of timesteps: ")
    timeSteps = int(timeSteps)
    if timeSteps>len(traj):
        print("Error: timestep selection is greater than timesteps in the trajectory file")
        return
    sampleAmount = input("Enter sample amount:")
    sampleAmount = int(sampleAmount)
    
    startTime = datetime.datetime.now()
    print("beginning proccess with ",timeSteps," timesteps, and ", sampleAmount, " samples, at ", startTime)
    
    samples=[]
    for i in range(sampleAmount):
        start = random.randint(0, (len(traj)-1)-timeSteps)
        end = start+timeSteps
        
        trajSample = traj[start:end]
        fluctSample = pt.atomicfluct(trajSample)
        corrSample = [pt.atomiccorr(trajSample)]
        
        dataArray = [trajSample, fluctSample, corrSample]
        samples.append(dataArray)
    
    print("Finished after: ", datetime.datetime.now()-startTime)
    return samples

In [5]:
import os
import IPython as py
import numpy as np
import math

In [6]:
#Searches the os for files that have .nc or .prmtop in their name.


def searchDir(dirArray):
    viableFiles = []
    for i in dirArray:
        length=len(i)
        trajIndex = i.find(".nc")
        topIndex = i.find(".prmtop")
        
        if length-(trajIndex)==3 or length-(topIndex)==7:
            if trajIndex != -1:
                viableFiles.append(i)
            if topIndex != -1:
                viableFiles.append(i)
            
    return viableFiles

def searchForFiles():
    path="/Users/"
    print(os.listdir(path))
    
    while True:
        py.display.clear_output()
        print("Path: ", path)
        dir = os.listdir(path)
        print("Directories: ")
        for i in dir:
            print("   ",i)
        print("useable files: ")
        udir=searchDir(dir)
        for i in udir:
            print("   ",i)
        
        
        command = input("choose a directory, type 'stop', or type 'choose' ")
        
        
        if command == 'choose':
            trajFile = input("type the name of the .nc file")
            topFile = input("type the name of the .prmtop file")
            
            return trajFile, topFile
        
        if command == 'stop':
            break
        for i in dir:
            if command==i:
                path=os.path.join(path, i)
            
        

In [7]:
def doEverything():
    trajFile, topFile = searchForFiles()
    
    traj = pt.load(trajFile, topFile)
    
    data = gatherData(traj)
    
    return traj

In [9]:
#all of the code is executed here. this runs off user input, but should later be changed to user interaction in 
#client side code.

traj = doEverything()

Path:  /Users/cjryan/Desktop/cpdWeb
Directories: 
    heat2.mdcrd
    main.cc
    cpptraj
    .DS_Store
    JShelloworld
    testingData_7c8j_bound_2
    trainingData
    heat1.mdcrd
    Functional vs NonFunctional movement.ipynb
    fluctuation and correlation calculating.ipynb
    TRPcage.prmtop
    main.wasm
    heat1.nc.gz
    emsdk
    .ipynb_checkpoints
    heat1.nc
    rustPython
useable files: 
    TRPcage.prmtop
    heat1.nc
choose a directory, type 'stop', or type 'choose' choose
type the name of the .nc fileheat1.nc
type the name of the .prmtop fileTRPcage.prmtop
Enter number of timesteps: 100
Enter sample amount:10
beginning proccess with  100  timesteps, and  10  samples, at  2021-10-23 21:53:37.300917
Finished after:  0:00:00.278003


In [10]:
traj

pytraj.Trajectory, 200 frames: 
Size: 0.001359 (GB)
<Topology: 304 atoms, 20 residues, 1 mols, non-PBC>
           

In [19]:
xyz = []
for i in traj.xyz:
    xyz.append(i[0])

In [20]:
xyz

[array([3.684, 1.703, 0.04 ]),
 array([3.68497439, 1.70719154, 0.04007372]),
 array([3.68672792, 1.70846008, 0.03867143]),
 array([3.68929333, 1.71179527, 0.03952081]),
 array([3.69221659, 1.72187964, 0.04176692]),
 array([3.69421679, 1.72933799, 0.04145076]),
 array([3.69908159, 1.73550766, 0.03985915]),
 array([3.70954164, 1.74700163, 0.04118506]),
 array([3.71614453, 1.75879698, 0.04418533]),
 array([3.72111521, 1.77145996, 0.04435429]),
 array([3.73077252, 1.78762821, 0.04347106]),
 array([3.7431223, 1.8033623, 0.0432624]),
 array([3.75281541, 1.82048085, 0.04335699]),
 array([3.76347247, 1.84040776, 0.04132908]),
 array([3.77953341, 1.86325156, 0.03899675]),
 array([3.79346802, 1.8842264 , 0.03768747]),
 array([3.80372778, 1.90386806, 0.03753619]),
 array([3.81413812, 1.92896596, 0.04013598]),
 array([3.83158381, 1.95604483, 0.04144605]),
 array([3.85194157, 1.97709434, 0.03903935]),
 array([3.86763941, 2.00010891, 0.04083079]),
 array([3.87648391, 2.02628706, 0.04747719]),
 array

In [13]:
import nglview as ngl

In [14]:
traj.superpose()
view = ngl.show_pytraj(traj)
view

NGLWidget(max_frame=199)

In [15]:
fluct = pt.atomicfluct(traj)

In [16]:
for i in fluct:
    print(i)

[1.         1.24887427]
[2.         1.34526213]
[3.         1.39367123]
[4.         1.24894928]
[5.         1.00316334]
[6.         1.02775922]
[7.         1.00364026]
[8.         1.17259542]
[9.         1.05589177]
[10.          0.90086747]
[11.          0.82556492]
[12.          1.06644271]
[13.          1.12290336]
[14.          1.22022954]
[15.          0.90996908]
[16.          0.98392592]
[17.          0.87530366]
[18.          0.86244775]
[19.          0.96052016]
[20.          0.99833623]
[21.          1.14412227]
[22.          1.18943642]
[23.          1.16116703]
[24.          1.33125234]
[25.         1.3387996]
[26.         1.3858877]
[27.          1.38518196]
[28.          1.56515728]
[29.          1.30138808]
[30.          1.54609469]
[31.          1.56363432]
[32.          1.69888039]
[33.         1.5727309]
[34.          0.93506494]
[35.          0.95880538]
[36.          0.93791998]
[37.          0.96860091]
[38.          0.92505171]
[39.         0.9268815]
[40.        

In [22]:
def customFluct(trajArray):
    fluct = 0
    
    
    
    refX = 0
    refY = 0
    refZ = 0
    for i in trajArray:
        refX+=i[0]
        refY+=i[1]
        refZ+=i[2]
    refX, refY, refZ = refX/len(trajArray), refY/len(trajArray), refZ/len(trajArray)
    
    sum = 0
    for i in trajArray:
        difX = i[0]-refX
        difY = i[1]-refY
        difZ = i[2]-refZ
        
        difX = pow(difX, 2)
        difY = pow(difY, 2)
        difZ = pow(difZ, 2)
        
        partial_sum = difX+difY+difZ
        sum+=partial_sum
    
    fluct = sum/len(trajArray)
    fluct = pow(fluct, 1/2)
            
            
        
    return fluct

In [23]:
customFluct(xyz)

1.2488742742192607

In [24]:
testArray = []
for i in range(304):
    arr = []
    for j in traj.xyz:
        arr.append(j[i])
    testArray.append(arr)

In [25]:
testArray[0]

[array([3.684, 1.703, 0.04 ]),
 array([3.68497439, 1.70719154, 0.04007372]),
 array([3.68672792, 1.70846008, 0.03867143]),
 array([3.68929333, 1.71179527, 0.03952081]),
 array([3.69221659, 1.72187964, 0.04176692]),
 array([3.69421679, 1.72933799, 0.04145076]),
 array([3.69908159, 1.73550766, 0.03985915]),
 array([3.70954164, 1.74700163, 0.04118506]),
 array([3.71614453, 1.75879698, 0.04418533]),
 array([3.72111521, 1.77145996, 0.04435429]),
 array([3.73077252, 1.78762821, 0.04347106]),
 array([3.7431223, 1.8033623, 0.0432624]),
 array([3.75281541, 1.82048085, 0.04335699]),
 array([3.76347247, 1.84040776, 0.04132908]),
 array([3.77953341, 1.86325156, 0.03899675]),
 array([3.79346802, 1.8842264 , 0.03768747]),
 array([3.80372778, 1.90386806, 0.03753619]),
 array([3.81413812, 1.92896596, 0.04013598]),
 array([3.83158381, 1.95604483, 0.04144605]),
 array([3.85194157, 1.97709434, 0.03903935]),
 array([3.86763941, 2.00010891, 0.04083079]),
 array([3.87648391, 2.02628706, 0.04747719]),
 array

In [28]:
for i in range(len(testArray)):
    print(customFluct(testArray[i]), fluct[i])

1.2488742742192607 [1.         1.24887427]
1.3452621311197521 [2.         1.34526213]
1.3936712257025328 [3.         1.39367123]
1.2489492779420643 [4.         1.24894928]
1.00316333805054 [5.         1.00316334]
1.0277592211504722 [6.         1.02775922]
1.0036402605948873 [7.         1.00364026]
1.172595417624734 [8.         1.17259542]
1.0558917684968627 [9.         1.05589177]
0.9008674673688012 [10.          0.90086747]
0.8255649160255725 [11.          0.82556492]
1.06644271235725 [12.          1.06644271]
1.1229033588248218 [13.          1.12290336]
1.2202295353124288 [14.          1.22022954]
0.9099690752745772 [15.          0.90996908]
0.9839259207032128 [16.          0.98392592]
0.8753036561535077 [17.          0.87530366]
0.8624477499044987 [18.          0.86244775]
0.9605201625865922 [19.          0.96052016]
0.9983362270176032 [20.          0.99833623]
1.1441222699644202 [21.          1.14412227]
1.189436424606194 [22.          1.18943642]
1.1611670299593664 [23.          1

In [71]:
import inspect

In [100]:
print(inspect.getsource(pt.atomicfluct))

@super_dispatch()
def rmsf(traj=None,
         mask="",
         top=None,
         dtype='ndarray',
         frame_indices=None,
         options=''):
    '''compute atomicfluct (RMSF)

    Parameters
    ----------
    traj : Trajectory-like
    mask : str or 1D-array
        atom mask. If not given, use all atoms
    options : str, additional cpptraj options ('byres', 'bymask', 'byatom', 'calcadp')

    Examples
    --------
    >>> import pytraj as pt
    >>> traj = pt.datafiles.load_tz2_ortho()
    >>> data = pt.rmsf(traj, '@CA') # or pt.atomicfluct
    >>> data[:3]
    array([[  5.        ,   0.61822273],
           [ 16.        ,   0.5627449 ],
           [ 40.        ,   0.53717119]])
    '''
    command = ' '.join((mask, options))
    c_dslist, _ = do_action(traj, command, c_action.Action_AtomicFluct)
    return get_data_from_dtype(c_dslist, dtype=dtype)

